samples:
  - SRR31533935
  - SRR31533936
  - SRR31533937
  - SRR31533938

Library:
  - p  # p for paired-end, s for single-end

reads:
  - 1
  - 2

fast5_dir: "samples/fast5"
kraken_db: "/mnt/omar/pipelines/ont/work/ref/kraken2"
bracken_db: "/mnt/omar/pipelines/ont/work/ref/kraken2"
humann_nuc_db: "/mnt/omar/misc/tests/chocophlan/chocophlan"
humann_prot_db: "/mnt/omar/misc/tests/uniref"
humann_kegg_db: "/mnt/omar/pipelines/ont/work/ref/humann/legacy/humann_legacy-0.99b/data/keggc"
predict_metabolites: "/mnt/omar/pipelines/ont/softwares/melonnpan/predict_metabolites.R"

threads: 11
threads_nt: 2

