samples:
  - ERR13731435
  - ERR13731454

reads:
  - 1
  - 2

fast5_dir: "samples/fast5"
kraken_db: "/mnt/omar/pipelines/ont/work/ref/kraken2"
bracken_db: "/mnt/omar/pipelines/ont/work/ref/kraken2"
humann_nuc_db: "/mnt/omar/pipelines/ont/work/ref/humann/chocophlan"
humann_prot_db: "/mnt/omar/pipelines/ont/work/ref/humann/uniref"
metadata_file: "path/to/metadata.csv"
humann_kegg_db: "/mnt/omar/pipelines/ont/work/ref/humann/legacy/humann_legacy-0.99b/data/keggc"

threads: 11
threads_nt: 2