# Load the necessary environments
configfile: "workflow/config.yml"

# include: "rules/001_basecall.smk"
# include: "rules/002_qc.smk"
# include: "rules/003_abundance.smk"
include: "rules/004_pathways.smk"
# include: "rules/005_amr.smk"
# include: "rules/006_tree.smk"
include: "rules/007_metabolites.smk"
include: "rules/010_multiqc.smk"

rule all:
    input:
        expand("results/multiqc/multiqc_report.html", sample=config["samples"]),
        expand("results/004_pathways/humann/{sample}/{sample}_kegg_pathways.tsv", sample=config["samples"]),
        expand(rules.melonnpan_prediction.output.metabolite_prediction, sample=config["samples"]),
